name: Release GW8 Staging - CI/CD Pipeline

on:
  push:
    branches:
      - staging
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    steps:
      - name: 🚀 Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST_STG }}
          port: ${{ secrets.DEPLOY_PORT_PROD }}
          username: ${{ secrets.DEPLOY_USER_PROD }}
          key: ${{ secrets.DEPLOY_KEY_PROD }}
          script: |
            sudo -S su
            cd /var/www/lenor-backend

            sudo git pull
            sudo npm install
            sudo pm2 delete server
            sudo pm2 start --name "server" index.js
